#!/usr/bin/env bash
# This script installs nginx on your server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start